#cloud-config
users:
  - name: appuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0f22fgzSq+Csqy4VsQ0JDDDUvlZXYhpaj+ggiDX+dUlkX2ZgbyKSSb8ZYmD+V0in+3rRtXNPSP27SzA7cvIkfyHJU8il2qUoKjxev/fnQkfh5e+SgiJ6dJyTUqHtRttChPA28YRQB4ajYwSsshAGcyckMZSAvAxO35UvaXT9Drq1LV2N9X0L5NyAnePUlEeBKkyIpJOTDuXhnFprfDWHUGG4XVfNPLxtOigSNLAoMDxkSvXs3oFCuo0Ie2lZKhLfoJeQ3XB/kAwZQ9gMp3zt9eyhnom+C6uroMhv0jTLVslfg/igAr8e5/XNEHKQigztU+31VjaQZhfpoyHP+JtEu9+/G/X6AIAItTJzmGs5bONltOfsSt1aA78wA+yyKEEs7g+X1rtzUY3SgUQsb6ivSwq5NDiZ+zStdIMvMDRxYuO+Aj4OKJ8FgYnzd2IXKHfIlXCDCSSq+o3qLdd+4vsazaCGmFdEKmyVs3UnJnC5KYY68hmFE9BjvFMUHtD0wAJE= appuser
package_update: true
write_files:
  - path: /home/appuser/startup_script.sh
    permissions: '0744'
    content: |
      #!/usr/bin/env bash
      echo "Preinstal step"
      sudo apt update
      sudo apt-get install apt-transport-https ca-certificates git -y

      ruby_inst=""
      rubyFull_is=$(dpkg --list | grep -i ruby-full -c)
      rubyBundl_is=$(dpkg --list | grep -i ruby-bundler -c)
      buildEss_is=$(dpkg --list | grep -i build-essential -c)
      if [ "$buildEss_is" -eq 0 ]
      then
       echo "Installing build-essential..."
       sudo apt update
       sudo apt install -y build-essential
      fi

      if [ "$rubyFull_is" -eq 0 ] && [ "$rubyBundl_is" -eq 0 ]
      then
       echo "Installing ruby-full ruby-bundler..."
       sudo apt update
       sudo apt install -y ruby-full ruby-bundler
      else
       if [ "$rubyFull_is" -eq 1 ] && [ "$rubyBundl_is" -eq 0 ]
        then
         echo "Installing ruby-bundler..."
         sudo apt update
         sudo apt install -y ruby-bundler
       fi
      fi

      gpg_key_is=$(apt-key list | grep 058F8B6B -c)
      if [ "$gpg_key_is" -eq 0 ]
      then
       wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
       echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      else
       echo "Mongokey is installed"
      fi

      mongo_is=$(dpkg --list | grep -i mongodb-org  -c)
      if [ "$mongo_is" -eq 0 ]
      then
       sudo apt update
       sudo apt install -y mongodb-org
      fi

      dbSvc_status=$(sudo systemctl status mongod | grep "Active: active (running)" -c)
      if [ "$dbSvc_status" -eq 0 ]
      then
       sudo systemctl start mongod
       sudo systemctl enable mongod
      fi


      cd ~
      git clone -b monolith https://github.com/express42/reddit.git
      if ! [ -d ~/reddit/ ]
      then
       echo "git clone failed"
       exit
      else
       cd ~/reddit
       bundle install
      fi

      puma_status=$(ps aux | grep puma | grep ":9292" -c)
      if [ "$puma_status" -eq 0 ]
      then
       puma_path=$(whereis puma | awk '{print $2}')
       if [ -x "$puma_path" ]
       then
        puma_path=$puma_path" -d"
        eval ${puma_path}
        puma_status=$(ps aux | grep puma | grep ":9292" -c)
        if [ "$puma_status" -eq 0 ]
        then
         echo "Puma's start failed"
         exit
        else
         echo "Puma starter successfully"
        fi
       fi
      else
       echo "Puma allready started"
      fi

runcmd:
 - [sudo, /home/appuser/startup_script.sh ]
